publish_to: https://pub.dev

name: words
version: 0.0.1+2

description: Collection of Dart linter rules used in WordCollector projects.

homepage: https://github.com/wordcollector/words
repository: https://github.com/wordcollector/words
issue_tracker: https://github.com/wordcollector/words/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
