name: words
version: 0.1.0+1

description: >-
  A curated collection of lints for use by Dart packages to ensure
  higher program safety and to promote best practices, selected and
  maintained by WordCollector.

homepage: https://github.com/wordcollector/words
repository: https://github.com/wordcollector/words
issue_tracker: https://github.com/wordcollector/words/issues

environment:
  sdk: '>=2.16.2 <3.0.0'
